# Generated by Django 4.2.1 on 2023-10-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('pasajeros', models.IntegerField()),
                ('comunaDestino', models.CharField(max_length=100)),
                ('Precio', models.IntegerField()),
                ('idPasajeros', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numero',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoDeUsuario',
            field=models.CharField(default='Pasajero', max_length=15),
        ),
    ]
